apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dispatcher-jira
  annotations:
    kubernetes.io/ingress.global-static-ip-name: lb-dispatcher-jira
    kubernetes.io/ingress.class: gce
    networking.gke.io/managed-certificates: dispatcher-jira
spec: 
  rules:
  - http: 
     paths: 
     - path: /healthy
       pathType: ImplementationSpecific
       backend: 
        service: 
          name: dispatcher-jira
          port: 
            number: 80
     - path: /queue-dispatcher-jira
       pathType: ImplementationSpecific
       backend:
         service: 
          name: dispatcher-jira
          port:
            number: 80 
     - path: /put-rule
       pathType: ImplementationSpecific
       backend:
         service: 
          name: dispatcher-jira
          port:
            number: 80
     - path: /rules
       pathType: ImplementationSpecific
       backend:
         service: 
          name: dispatcher-jira
          port:
            number: 80
